// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/user/appUserRole.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface CreateAppUserRoleInput {
    userId: string;
    roleId: string;
}

export interface BulkAssignRolesInput {
    userId: string;
    roleIds: string[];
}
