// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/common/audit.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface SysDetails {
    version?: number;
    createdBy: string;
    updatedBy?: string;
    deletedBy?: string;
    auditTrail: AuditEntry[];
}

interface AuditEntry {
    actor?: string;
    request?: object;
    operation?: string;
    ocurredAt?: Date;
}

export interface AppDetails {
    createdAt: Date;
    user: string;
    method: string;
    detail: string;
}