// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/diagnosticTerm/diagnosticTerm.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

import type { TermSource } from './common';

// code is required here even though the DDL admits null: with every row coded, the unique pair
// (source, code) protects the whole table. An API stricter than the schema is the safe direction.
// source is optional on create — it defaults to 'LOCAL' — and immutable on update, where it is
// ignored in silence so a client resending the GET response does not get a 400 for a field it
// never meant to change.
// metadata is deliberately absent: it is not writable from the API. reviewStatus is the only door
// to its content, arrives flat and is merged over the stored object, preserving autoCreated and
// createdFrom
export interface CreateDiagnosticTermInput {
    source?: TermSource;
    code: string;
    name: string;
    termGroup?: string | null;
    reviewStatus?: string;
    isActive?: boolean;
}

// Query filters of the two listings. search is the legacy alias: name OR code. name and code are
// the canonical parameters (SPEC F52), each an Op.iLike over its own column. source and termGroup
// are exact equality. reviewStatus resolves over the metadata.reviewStatus JSONB key and is
// admitted by the admin listing alone — the public one has no business filtering a review queue
export interface DiagnosticTermListFilters {
    search?: string;
    name?: string;
    code?: string;
    source?: TermSource;
    termGroup?: string;
    reviewStatus?: string;
}

// Input of the implicit resolution service (ESAVI-DIAGTERM-006). source is not a parameter: it is
// always LOCAL. operationCode is the code of the endpoint that triggered the resolution, and it is
// stored in metadata.createdFrom so an autogenerated term can be traced back to what created it
export interface ResolveDiagnosticTermInput {
    code: string;
    name: string;
    operationCode: string;
}

// Body of the bulk import (ESAVI-DIAGTERM-007). It carries no code and no name: the data comes from
// the uploaded file, never from the body. dictionaryVersion is free text and is only kept inside the
// metadata of each imported row — there is no dictionary version table in this spec
export interface ImportDiagnosticTermsInput {
    source?: TermSource;
    termGroup?: string;
    dictionaryVersion?: string;
    encoding?: 'utf8' | 'latin1';
    dryRun?: boolean;
}

// One accepted line of the .asc file. line is 1-based so the report points at the file the way the
// operator sees it in an editor
export interface ParsedDiagnosticTermRow {
    line: number;
    code: string;
    name: string;
    isActive: boolean;
}

// One rejected line. raw is trimmed to 200 characters: a binary file uploaded by mistake would
// otherwise put whole megabytes into the response
export interface RejectedDiagnosticTermRow {
    line: number;
    reason: 'EMPTY_CODE' | 'EMPTY_NAME' | 'CODE_TOO_LONG' | 'NAME_TOO_LONG' | 'MISSING_FIELDS' | 'DUPLICATE_IN_FILE';
    raw: string;
}

// What the import returns instead of a resource: the report of a process. The counters are exact;
// errors carries only the first 20 entries
export interface DiagnosticTermImportReport {
    read: number;
    inserted: number;
    updated: number;
    unchanged: number;
    invalid: number;
    duplicated: number;
    dryRun: boolean;
    source: TermSource;
    termGroup: string;
    errors: RejectedDiagnosticTermRow[];
}
