// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/investigation/evaluationInstitution.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

// Unlike investigationPregnancyCondition, no input key stops being a column here: this entity
// resolves nothing against any master, so what the client sends is what gets stored — normalized
// and, in two cases, encrypted.
//
// Two deliberate absences. evaluationInstitutionId is generated by the database. And sortOrder is
// not here because it is immutable and assigned by TRG_evaluationInstitution_setSortOrder — keeping
// it out of the type is the cheapest guarantee that no service ever sends it.
//
// investigationId names the clinical evaluation and not the investigation: it is the primary key of
// investigationClinicalEvaluation, which happens to be the same UUID because that table shares its
// key with its parent.
//
// healthFacilityId and institutionName coexist on purpose, and at least one of the two must end up
// with a value — a rule the service enforces and the validator cannot, because in the update it
// depends on the stored state and not only on the body.
//
// The update uses Partial<CreateEvaluationInstitutionInput>: no UpdateEvaluationInstitutionInput
// exists
export interface CreateEvaluationInstitutionInput {
    investigationId: string;
    healthFacilityId?: string | null;
    institutionName?: string | null;
    personName?: string | null;
    personContact?: string | null;
    evaluationInstitutionTypeItemId?: string | null;
    notes?: string | null;
    isActive?: boolean;
}
