// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/geography/geoLevelType.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface CreateGeoLevelTypeInput {
    code: string;
    name: string;
    sortOrder: number;
}