// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/geography/geoLocation.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface CreateGeoLocationInput {
    geoLevelTypeId: string;
    parentGeoLocationId?: string | null;
    name: string;
    shortName?: string | null;
    officialName?: string | null;
    isoCode?: string | null;
    externalCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    sortOrder?: number | null;
    level?: number | null;
    geoPolygon?: object | null;
}