// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/geography/geoLevelType.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface CreateGeoLevelTypeInput {
    code: string;
    name: string;
    sortOrder: number;
}

// Query filters of the two listings, identical in both. name and code are the canonical
// parameters (SPEC F52), each an Op.iLike over its own column, joined with Op.or. There is no
// legacy search alias here: the entity had no text filter at all before this spec
export interface GeoLevelTypeListFilters {
    name?: string;
    code?: string;
}