// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.
// Mirror of esavi-backend/src/types/patient/patient.types.ts
// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).

export interface CreatePatientInput {
    names: string;
    lastNames: string;
    documentNumber: string;
    birthDate?: string | null;
    passportNumber?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    sexItemId?: string | null;
    residenceGeoLocationId?: string | null;
    isActive?: boolean;
}
