// Copies types from ../esavi-backend/src/types to src/contracts/, as-is — no curating exports,
// no infrastructure (ARCHITECTURE.md §10). A backend change shows up whole in the diff.
//
// src/contracts/declared/ is NEVER touched here: those are shapes the backend builds as
// literals (no `interface` to copy, see CONVENTIONS.md §9 and SPEC FE01 §3.3) and are
// reconciled by hand.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BACKEND_TYPES_DIR = path.resolve(__dirname, '../../esavi-backend/src/types');
const CONTRACTS_DIR = path.resolve(__dirname, '../src/contracts');

// Which backend file produces which frontend contract. Grows as each spec declares, in its
// §3.3, which types it consumes — never synced ahead of time for something nobody uses yet.
const SYNC_MAP = [
  { source: 'user/user.types.ts', dest: 'user.ts' },
  { source: 'common/audit.types.ts', dest: 'common.ts' },
];

function buildHeader(sourceRelPath) {
  return (
    '// Generated by `npm run contracts:sync` — DO NOT EDIT BY HAND.\n' +
    `// Mirror of esavi-backend/src/types/${sourceRelPath}\n` +
    '// Anything hand-written goes in src/contracts/declared/ (CONVENTIONS.md §3, §9).\n\n'
  );
}

if (!existsSync(BACKEND_TYPES_DIR)) {
  console.error(`contracts:sync — no encuentro esavi-backend/src/types en ${BACKEND_TYPES_DIR}.`);
  console.error(
    'esavi-backend debe estar clonado como carpeta hermana de esavi-frontend (CLAUDE.md).',
  );
  process.exit(1);
}

let synced = 0;
for (const { source, dest } of SYNC_MAP) {
  const sourcePath = path.join(BACKEND_TYPES_DIR, source);
  if (!existsSync(sourcePath)) {
    console.error(`contracts:sync — no existe src/types/${source} en esavi-backend.`);
    process.exit(1);
  }
  const content = readFileSync(sourcePath, 'utf-8');
  writeFileSync(path.join(CONTRACTS_DIR, dest), buildHeader(source) + content);
  console.log(`✔ ${dest} ← esavi-backend/src/types/${source}`);
  synced++;
}

console.log(`\ncontracts:sync — ${synced} archivo(s) sincronizado(s).`);
process.exit(0);
